name: dev
on:
  pull_request:
  push:
    branches:
      - master
env:
  CI: true

jobs:
  prettier:
    name: Format code
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prettier
        uses: gulpjs/prettier_action@v3.0
        with:
          commit_message: 'Build: Run prettier'
          prettier_options: '--write .'

  test:
    name: Tests for Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          TEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
